Fix: handle case when user is None during password change check
If the user was not found, this caused an 
AttributeError: 'NoneType' object has no attribute 'last_sign_in_at'